#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

export TRAIN_FROM_SCRATCH=${TRAIN_FROM_SCRATCH:-1}
export NUM_EPOCHS=${NUM_EPOCHS:-256}
export BATCH_SIZE=${BATCH_SIZE:-256}
export OPTIMIZER=${OPTIMIZER:-adam}
export LR=${LR:-0.01}
export LUT_LR=${LUT_LR:-0.01}
export SCHEDULE=${SCHEDULE:-linear}
export LUT_SCHEDULE=${LUT_SCHEDULE:-linear}
export WEIGHT_DECAY=${WEIGHT_DECAY:-0}
export CLIPNORM=${CLIPNORM:-0}
export CLIPVAL=${CLIPVAL:-0}
export LUT_TRAINING_MODE=${LUT_TRAINING_MODE:-real_compatible}
export LUT_INIT_MODE=${LUT_INIT_MODE:-bimodal}
export LUT_BIMODAL_NEGATIVE_MEAN=${LUT_BIMODAL_NEGATIVE_MEAN:--1.0}
export LUT_BIMODAL_NEGATIVE_STD=${LUT_BIMODAL_NEGATIVE_STD:-0.2}
export LUT_BIMODAL_POSITIVE_MEAN=${LUT_BIMODAL_POSITIVE_MEAN:-1.0}
export LUT_BIMODAL_POSITIVE_STD=${LUT_BIMODAL_POSITIVE_STD:-0.1}
export AUGMENTATION=${AUGMENTATION:-real_lut}
export LABEL_SMOOTHING=${LABEL_SMOOTHING:-0.1}
export NO_VALIDATION=${NO_VALIDATION:-1}

exec "$ROOT_DIR/run_phase3.sh" "$@"
